### ISSUE TITLE
Problem with cmake build on MacOS with SDK 15.4

### ISSUE THREAD

**Issue by Masterlovsky** [eclipse-paho/paho.mqtt.cpp#553]
How do I resolve the following compilation errors? I get an error when compiling the paho project on a Mac with an M4 chip and MacOSX15.4.sdk; But it's fine on a laptop with an M2 chip, and it's no problem on a macbook with x64 architecture.

[  6%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/async_client.cpp.o
In file included from /Users/masterlovsky/work/paho/paho.mqtt.cpp-master/src/async_client.cpp:20:
In file included from /Users/masterlovsky/work/paho/paho.mqtt.cpp-master/src/mqtt/async_client.h:29:
In file included from /Users/masterlovsky/work/paho/paho.mqtt.cpp-master/src/mqtt/types.h:26:
/Library/Developer/CommandLineTools/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/string:821:42: error: implicit instantiation of undefined template 'std::char_traits<unsigned char>'
  821 |   static_assert(is_same<_CharT, typename traits_type::char_type>::value,
      |                                          ^
/Users/masterlovsky/work/paho/paho.mqtt.cpp-master/src/mqtt/ssl_options.h:103:35: note: in instantiation of template class 'std::basic_string<unsigned char>' requested here
  103 |         std::basic_string<unsigned char> protos_;
      |                                          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/__fwd/string.h:23:29: note: template is declared here
   23 | struct _LIBCPP_TEMPLATE_VIS char_traits;
      |                             ^
1 error generated.
make[2]: *** [src/CMakeFiles/paho-cpp-objs.dir/async_client.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/paho-cpp-objs.dir/all] Error 2
make: *** [all] Error 2

**Comment by kuroneko** [comment]
Duplicate of #544 / #548

**Comment by fpagliughi** [comment]
This is fixed in v1.5.3.
